### ISSUE TITLE
How to apply public symbol file?

### ISSUE THREAD

**Issue by lizhangqu** [xyxyLiu/AndResM#2]
Now I use 0x30 for packageId PP, how to apply exported symbol file in order to keep resource id not modify.

I have a try with aapt, it can easily export symble file by add "-P" param and copy symbol file to buildDir/intermediates/$buildType/res/values to apply it.

But when use aapt2,error will happed

```
Error:can't assign ID 0x30000000 to resource packageName:resourceType/resourceName with conflicting ID 0x7f000000.
```

**Comment by xyxyLiu** [comment]
AndresM only handle the output of AAPT, it will modify all the PP part in PPTTNNNN in final, So it can not support id-keeping for now. But we can add a small modification to enable it.

**Comment by lizhangqu** [comment]
Now I changed the export symbol file from 0xPP to 0x7f in order to keep id , and then change the output file(like arsc) from 0x7f to 0xPP again. it woks fine!

But I found a new problem. I need to add -I param to refrence the files's resId like the android.jar. and the resId is 0x7f but it's in other reource ap file.  AndresM will also modify the id which can't be modified

**Comment by xyxyLiu** [comment]
AndresM now supports android-gradle-plugin 3.0+, maybe you can try it with android-gradle-plugin 3.0 if you are using aapt2
